### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by JavaProgswing** [sijey-praveen/YouTube-Music-API#2]
'NoneType' object has no attribute 'get' in YouTubeMusicAPI("Lily").track() .

**Comment by sijey-praveen** [comment]
> 'NoneType' object has no attribute 'get' in YouTubeMusicAPI("Lily").track() .

![cmd_734DiNgpSZ](https://user-images.githubusercontent.com/80583308/144248800-6a1944a4-efe7-4955-90ef-5558b20cc90a.png)

**It Works Well!**
From Which Country you're using executing the code?
Countries like Bangladesh etc... Banned YouTube

**Comment by JavaProgswing** [comment]
File "/python/lib/python3.8/site-packages/YouTubeMusicAPI/__init__.py", line 41, in track
    name = __src__.find("meta", attrs={"name" : "title"}).get("content"),

**Comment by JavaProgswing** [comment]
It used to work before , I dont know what happened.
I am not from bangladesh though.

**Comment by JavaProgswing** [comment]
Is there a ratelimit that could 'cause this?

**Comment by sijey-praveen** [comment]
```pip uninstall YouTubeMusicAPI```

```pip install --upgrade YouTubeMusicAPI==2.3```

**Comment by sijey-praveen** [comment]
> Is there a ratelimit that could 'cause this?

Nope, It's Free!

**Comment by JavaProgswing** [comment]
Did uninstall and reinstall , no change.

**Comment by sijey-praveen** [comment]
> Did uninstall and reinstall , no change.

Same Error?

**Comment by JavaProgswing** [comment]
Yes  'AttributeError' object has no attribute 'traceback'

**Comment by JavaProgswing** [comment]
Yes "AttributeError: 'NoneType' object has no attribute 'get'"

**Comment by JavaProgswing** [comment]
Traceback (most recent call last):
  File "<string>", line 3, in __ex
  File "/app/python/lib/python3.8/site-packages/YouTubeMusicAPI/__init__.py", line 41, in track
    name = __src__.find("meta", attrs={"name" : "title"}).get("content"),
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by sijey-praveen** [comment]
> Yes "AttributeError: 'NoneType' object has no attribute 'get'"

Can You Contact Me on Discord?
**Sijey#9115**

**Comment by JavaProgswing** [comment]
Ok i sent you friend request.
