### ISSUE TITLE
No Result Found!

### ISSUE THREAD

**Issue by VladGrz** [sijey-praveen/YouTube-Music-API#3]
It worked well some time ago but now I get `No Result Found!` for all titles, even for those that were found before.

**Comment by sijey-praveen** [comment]
> It worked well some time ago but now I get `No Result Found!` for all titles, even for those that were found before.

can i see your code?

**Comment by VladGrz** [comment]
Yep
![image](https://user-images.githubusercontent.com/60891301/167248495-c75b53ab-6237-4aea-b776-d6e916ffe8c1.png)

Basically it gets title from different library for track recognition, but after problem I tried some specified titles, such as in an example:
```
search_res = YouTubeMusicAPI().track("immortals")
print(search_res)
if type(search_res) is str:
    return None, None
return search_res['url'], search_res['image']
```
Result is the same

**Comment by sijey-praveen** [comment]
> 

## This code actually works without any errors

```py
from YouTubeMusicAPI import YouTubeMusicAPI

def get_ytm_track(title):
    search_res = YouTubeMusicAPI().track(title)
    print(search_res)
    if type(search_res) is str:
        return None, None
    return search_res['url'], search_res['image']

for i in ["faded", "alan walker new", "shape of you", "godzilla title track"]:
    print(get_ytm_track(i))
```

### Output

```
{'name': 'Alan Walker - Faded', 'datePublished': '2015-12-03', 'Id': '60ItHLz5WEA', 'url': 'https://music.youtube.com/watch?v=60ItHLz5WEA', 'image': 'https://i.ytimg.com/vi/60ItHLz5WEA/hqdefault.jpg'}
('https://music.youtube.com/watch?v=60ItHLz5WEA', 'https://i.ytimg.com/vi/60ItHLz5WEA/hqdefault.jpg')
{'name': 'Alan Walker - The Drum (Official Music Video)', 'datePublished': '2022-04-29', 'Id': 'TicGJQqrq2M', 'url': 'https://music.youtube.com/watch?v=TicGJQqrq2M', 'image': 'https://i.ytimg.com/vi/TicGJQqrq2M/hqdefault.jpg'}
('https://music.youtube.com/watch?v=TicGJQqrq2M', 'https://i.ytimg.com/vi/TicGJQqrq2M/hqdefault.jpg')
{'name': 'Ed Sheeran - Shape of You (Official Music Video)', 'datePublished': '2017-01-30', 'Id': 'JGwWNGJdvx8', 'url': 'https://music.youtube.com/watch?v=JGwWNGJdvx8', 'image': 'https://i.ytimg.com/vi/JGwWNGJdvx8/hqdefault.jpg'}
('https://music.youtube.com/watch?v=JGwWNGJdvx8', 'https://i.ytimg.com/vi/JGwWNGJdvx8/hqdefault.jpg')
{'name': 'Godzilla: King Of The Monsters Official Soundtrack | Main Title - Bear McCreary | WaterTower', 'datePublished': '2019-05-23', 'Id': 'cD0FeOrK6rk', 'url': 'https://music.youtube.com/watch?v=cD0FeOrK6rk', 'image': 'https://i.ytimg.com/vi/cD0FeOrK6rk/hqdefault.jpg'}
('https://music.youtube.com/watch?v=cD0FeOrK6rk', 'https://i.ytimg.com/vi/cD0FeOrK6rk/hqdefault.jpg')
```

**Comment by sijey-praveen** [comment]
> Yep ![image](https://user-images.githubusercontent.com/60891301/167248495-c75b53ab-6237-4aea-b776-d6e916ffe8c1.png)
> 
> Basically it gets title from different library for track recognition, but after problem I tried some specified titles, such as in an example:
> 
> ```
> search_res = YouTubeMusicAPI().track("immortals")
> print(search_res)
> if type(search_res) is str:
>     return None, None
> return search_res['url'], search_res['image']
> ```
> 
> Result is the same

whether this song doesn't exist on yt music
or can you tell me for which query you are facing this error
if i see the query i can sort it out.

**Comment by VladGrz** [comment]
> 
Tried your code, unfortunately same result. May be trouble is in Python version? Which version do you use?

```
No Result Found!
(None, None)
No Result Found!
(None, None)
No Result Found!
(None, None)
No Result Found!
(None, None)
```

**Comment by sijey-praveen** [comment]
> 

Python 3.10.0

**Comment by sijey-praveen** [comment]
> > 
> 
> Tried your code, unfortunately same result. May be trouble is in Python version? Which version do you use?
> 
> ```
> No Result Found!
> (None, None)
> No Result Found!
> (None, None)
> No Result Found!
> (None, None)
> No Result Found!
> (None, None)
> ```

```
Armenia
Afghanistan
Brazil
Germany
Bangladesh
Libya
Morocco
Malaysia
Indonesia
Pakistan
Russia
Sudan
Syria
Tajikistan[[8]](https://youtube.fandom.com/wiki/Countries_that_have_blocked_YouTube#cite_note-8)
Thailand
Tunisia
Turkey
United Arab Emirates
Venezuela
```
### Are you using my library from any of this country listed above, If yes Youtube and youtube music are banned there. So the Web Request can made

**Comment by VladGrz** [comment]
> > Yep ![image](https://user-images.githubusercontent.com/60891301/167248495-c75b53ab-6237-4aea-b776-d6e916ffe8c1.png)
> > Basically it gets title from different library for track recognition, but after problem I tried some specified titles, such as in an example:
> > ```
> > search_res = YouTubeMusicAPI().track("immortals")
> > print(search_res)
> > if type(search_res) is str:
> >     return None, None
> > return search_res['url'], search_res['image']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Result is the same
> 
> whether this song doesn't exist on yt music or can you tell me for which query you are facing this error if i see the query i can sort it out.

Here are some track`s titles that worked well and were found in ytmusic. 
["Mareux  - Spectral Tease", "Relanium  - Leel Lost (Reloaded) [Extended Mix]", "Taco  - Puttin' On The Ritz", "Archie  - Space Pirates"]
Also last time the track "Taco  - Puttin' On The Ritz" was found is on 24th april 2022, after that I didn`t use my bot for searching and now i tried and got that result.

**Comment by VladGrz** [comment]
> > > 
> > 
> > 
> > Tried your code, unfortunately same result. May be trouble is in Python version? Which version do you use?
> > ```
> > No Result Found!
> > (None, None)
> > No Result Found!
> > (None, None)
> > No Result Found!
> > (None, None)
> > No Result Found!
> > (None, None)
> > ```
> 
> ```
> Armenia
> Afghanistan
> Brazil
> Germany
> Bangladesh
> Libya
> Morocco
> Malaysia
> Indonesia
> Pakistan
> Russia
> Sudan
> Syria
> Tajikistan[[8]](https://youtube.fandom.com/wiki/Countries_that_have_blocked_YouTube#cite_note-8)
> Thailand
> Tunisia
> Turkey
> United Arab Emirates
> Venezuela
> ```
> 
> ### Are you using my library from any of this country listed above, If yes Youtube and youtube music are banned there. So the Web Request can made

No, I'm from Ukraine

**Comment by VladGrz** [comment]
May be switching Python versions will help me.

**Comment by sijey-praveen** [comment]
> 


> May be switching Python versions will help me.

wait

**Comment by sijey-praveen** [comment]
> > > Yep ![image](https://user-images.githubusercontent.com/60891301/167248495-c75b53ab-6237-4aea-b776-d6e916ffe8c1.png)
> > > Basically it gets title from different library for track recognition, but after problem I tried some specified titles, such as in an example:
> > > ```
> > > search_res = YouTubeMusicAPI().track("immortals")
> > > print(search_res)
> > > if type(search_res) is str:
> > >     return None, None
> > > return search_res['url'], search_res['image']
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Result is the same
> > 
> > 
> > whether this song doesn't exist on yt music or can you tell me for which query you are facing this error if i see the query i can sort it out.
> 
> Here are some track's titles that worked well and were found in ytmusic. `["Mareux - Spectral Tease", "Relanium - Leel Lost (Reloaded) [Extended Mix]", "Taco - Puttin' On The Ritz", "Archie - Space Pirates"]` Also last time the track "Taco - Puttin' On The Ritz" was found is on 24th april 2022, after that I didn't use my bot for searching and now i tried and got that result.

```py
from requests import get

def get_ytm_track(title):
    search_res = get("https://httpbin.sijey.repl.co/youtubemusic/search?search_query={}".format(title)).json()
    print(search_res)
    if type(search_res) is str:
        return None, None
    return search_res['url'], search_res['image']

for i in ["Mareux - Spectral Tease", "Relanium - Leel Lost (Reloaded) [Extended Mix]", "Taco - Puttin' On The Ritz", "Archie - Space Pirates"]:
    print(get_ytm_track(i))

```

**Comment by VladGrz** [comment]
> > > > Yep ![image](https://user-images.githubusercontent.com/60891301/167248495-c75b53ab-6237-4aea-b776-d6e916ffe8c1.png)
> > > > Basically it gets title from different library for track recognition, but after problem I tried some specified titles, such as in an example:
> > > > ```
> > > > search_res = YouTubeMusicAPI().track("immortals")
> > > > print(search_res)
> > > > if type(search_res) is str:
> > > >     return None, None
> > > > return search_res['url'], search_res['image']
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Result is the same
> > > 
> > > 
> > > whether this song doesn't exist on yt music or can you tell me for which query you are facing this error if i see the query i can sort it out.
> > 
> > 
> > Here are some track's titles that worked well and were found in ytmusic. `["Mareux - Spectral Tease", "Relanium - Leel Lost (Reloaded) [Extended Mix]", "Taco - Puttin' On The Ritz", "Archie - Space Pirates"]` Also last time the track "Taco - Puttin' On The Ritz" was found is on 24th april 2022, after that I didn't use my bot for searching and now i tried and got that result.
> 
> ```python
> from requests import get
> 
> def get_ytm_track(title):
>     search_res = get("https://httpbin.sijey.repl.co/youtubemusic/search?search_query={}".format(title)).json()
>     print(search_res)
>     if type(search_res) is str:
>         return None, None
>     return search_res['url'], search_res['image']
> 
> for i in ["Mareux - Spectral Tease", "Relanium - Leel Lost (Reloaded) [Extended Mix]", "Taco - Puttin' On The Ritz", "Archie - Space Pirates"]:
>     print(get_ytm_track(i))
> ```

It worked!

**Comment by sijey-praveen** [comment]
> > > > > Yep ![image](https://user-images.githubusercontent.com/60891301/167248495-c75b53ab-6237-4aea-b776-d6e916ffe8c1.png)
> > > > > Basically it gets title from different library for track recognition, but after problem I tried some specified titles, such as in an example:
> > > > > ```
> > > > > search_res = YouTubeMusicAPI().track("immortals")
> > > > > print(search_res)
> > > > > if type(search_res) is str:
> > > > >     return None, None
> > > > > return search_res['url'], search_res['image']
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Result is the same
> > > > 
> > > > 
> > > > whether this song doesn't exist on yt music or can you tell me for which query you are facing this error if i see the query i can sort it out.
> > > 
> > > 
> > > Here are some track's titles that worked well and were found in ytmusic. `["Mareux - Spectral Tease", "Relanium - Leel Lost (Reloaded) [Extended Mix]", "Taco - Puttin' On The Ritz", "Archie - Space Pirates"]` Also last time the track "Taco - Puttin' On The Ritz" was found is on 24th april 2022, after that I didn't use my bot for searching and now i tried and got that result.
> > 
> > 
> > ```python
> > from requests import get
> > 
> > def get_ytm_track(title):
> >     search_res = get("https://httpbin.sijey.repl.co/youtubemusic/search?search_query={}".format(title)).json()
> >     print(search_res)
> >     if type(search_res) is str:
> >         return None, None
> >     return search_res['url'], search_res['image']
> > 
> > for i in ["Mareux - Spectral Tease", "Relanium - Leel Lost (Reloaded) [Extended Mix]", "Taco - Puttin' On The Ritz", "Archie - Space Pirates"]:
> >     print(get_ytm_track(i))
> > ```
> 
> It worked!

nice get us get in touch 

cause https://httpbin.sijey.repl.co/ the site is owned by me
now for temporary i hosted the YouTubeMusicAPI script there so once the problem got fixed let me inform you
you have discord?

**Comment by VladGrz** [comment]
Yes, I have. vladgroz#5052 that is my tag. Thanks for fast fix

**Comment by sijey-praveen** [comment]
> 

friend request send 
accept it lets continue there

also this issue will be closed
thanks for contacting me
